__author__ = 'Naveed'

JSON_KEY_STATUS_CODE        = "status_code"
JSON_KEY_STATUS_MESSAGE     = "status_message"

def OK():
    return {JSON_KEY_STATUS_CODE : 1     , JSON_KEY_STATUS_MESSAGE : "OK"}

def WRONG_HTTP_METHOD_CALLED():
    return {JSON_KEY_STATUS_CODE : 901    , JSON_KEY_STATUS_MESSAGE : "WRONG_HTTP_METHOD_CALLED"}

def INVALID_UDID_OR_TOKEN():
    return {JSON_KEY_STATUS_CODE : 110     , JSON_KEY_STATUS_MESSAGE : "INVALID_UDID_OR_TOKEN"}

def INVALID_FORM_POSTED():
    return {JSON_KEY_STATUS_CODE : 511    , JSON_KEY_STATUS_MESSAGE : "INVALID_FORM_POSTED"}

def REQUEST_PARAM_MISSING():
    return {JSON_KEY_STATUS_CODE : 301    , JSON_KEY_STATUS_MESSAGE : "REQUEST_PARAMS_MISSING"}

def USER_NOT_FOUND():
    return {JSON_KEY_STATUS_CODE : 401    , JSON_KEY_STATUS_MESSAGE : "USER_NOT_FOUND"}